#############################################################################
# Makefile for building: libEasyMotion.so
# Generated by qmake (2.01a) (Qt 4.8.4) on: Mon Feb 17 10:42:23 2014
# Project:  easymotion.pro
# Template: lib
# Command: /usr/bin/qmake -o Makefile easymotion.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DEASYMOTION_LIBRARY -DIDE_LIBRARY_BASENAME=\"lib\" -DQT_CREATOR -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_USE_FAST_OPERATOR_PLUS -DQT_USE_FAST_CONCATENATION -DQT_NO_DEBUG -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -fvisibility=hidden -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I../../../test/qt-creator-2.8.1-src/src -I../../../test/qt-creator-2.8.1-src/src/libs -I/home/xwu/test/qt-creator-2.8.1-src/tools -I../../../test/qt-creator-2.8.1-src/src/plugins -I.moc/release-shared
LINK          = g++
LFLAGS        = -m64 -Wl,-z,origin '-Wl,-rpath,$$ORIGIN:$$ORIGIN/..:$$ORIGIN/../..' -Wl,--no-undefined -Wl,-O1 -shared -Wl,-soname,libEasyMotion.so
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/home/xwu/test/qt-creator-2.8.1-src/lib/qtcreator -lCore -lExtensionSystem -lUtils -lAggregation -L/home/xwu/test/qt-creator-2.8.1-src/lib/qtcreator/plugins/QtProject -L/home/xwu/test/qt-creator-2.8.1-src/lib/qtcreator/plugins/XiaofengWu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = .obj/release-shared/

####### Files

SOURCES       = easymotionplugin.cpp .moc/release-shared/moc_easymotionplugin.cpp
OBJECTS       = .obj/release-shared/easymotionplugin.o \
		.obj/release-shared/moc_easymotionplugin.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		EasyMotion_dependencies.pri \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/coreplugin_dependencies.pri \
		../../../test/qt-creator-2.8.1-src/src/libs/extensionsystem/extensionsystem_dependencies.pri \
		../../../test/qt-creator-2.8.1-src/src/libs/utils/utils_dependencies.pri \
		../../../test/qt-creator-2.8.1-src/src/libs/aggregation/aggregation_dependencies.pri \
		../../../test/qt-creator-2.8.1-src/qtcreator.pri \
		../../../test/qt-creator-2.8.1-src/src/qtcreatorplugin.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/hide_symbols.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		EasyMotion.pluginspec.in \
		easymotion.pro
QMAKE_TARGET  = EasyMotion
DESTDIR       = ../../../test/qt-creator-2.8.1-src/lib/qtcreator/plugins/XiaofengWu/
TARGET        = libEasyMotion.so
TARGETD       = libEasyMotion.so

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  ../../../test/qt-creator-2.8.1-src/lib/qtcreator/plugins/XiaofengWu/$(TARGET)

../../../test/qt-creator-2.8.1-src/lib/qtcreator/plugins/XiaofengWu/$(TARGET): ../../../test/qt-creator-2.8.1-src/lib/qtcreator/plugins/XiaofengWu/EasyMotion.pluginspec $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@$(CHK_DIR_EXISTS) ../../../test/qt-creator-2.8.1-src/lib/qtcreator/plugins/XiaofengWu/ || $(MKDIR) ../../../test/qt-creator-2.8.1-src/lib/qtcreator/plugins/XiaofengWu/ 
	-$(DEL_FILE) $(TARGET)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-$(MOVE) $(TARGET) ../../../test/qt-creator-2.8.1-src/lib/qtcreator/plugins/XiaofengWu/



Makefile: easymotion.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		EasyMotion_dependencies.pri \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/coreplugin_dependencies.pri \
		../../../test/qt-creator-2.8.1-src/src/libs/extensionsystem/extensionsystem_dependencies.pri \
		../../../test/qt-creator-2.8.1-src/src/libs/utils/utils_dependencies.pri \
		../../../test/qt-creator-2.8.1-src/src/libs/aggregation/aggregation_dependencies.pri \
		../../../test/qt-creator-2.8.1-src/qtcreator.pri \
		../../../test/qt-creator-2.8.1-src/src/qtcreatorplugin.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/hide_symbols.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		EasyMotion.pluginspec.in \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile easymotion.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
EasyMotion_dependencies.pri:
../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/coreplugin_dependencies.pri:
../../../test/qt-creator-2.8.1-src/src/libs/extensionsystem/extensionsystem_dependencies.pri:
../../../test/qt-creator-2.8.1-src/src/libs/utils/utils_dependencies.pri:
../../../test/qt-creator-2.8.1-src/src/libs/aggregation/aggregation_dependencies.pri:
../../../test/qt-creator-2.8.1-src/qtcreator.pri:
../../../test/qt-creator-2.8.1-src/src/qtcreatorplugin.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/hide_symbols.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
EasyMotion.pluginspec.in:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile easymotion.pro

dist: 
	@$(CHK_DIR_EXISTS) .obj/release-shared/EasyMotion1.0.0 || $(MKDIR) .obj/release-shared/EasyMotion1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .obj/release-shared/EasyMotion1.0.0/ && $(COPY_FILE) --parents EasyMotion.pluginspec .obj/release-shared/EasyMotion1.0.0/ && $(COPY_FILE) --parents easymotionplugin.h easymotion_global.h easymotionconstants.h .obj/release-shared/EasyMotion1.0.0/ && $(COPY_FILE) --parents easymotionplugin.cpp .obj/release-shared/EasyMotion1.0.0/ && (cd `dirname .obj/release-shared/EasyMotion1.0.0` && $(TAR) EasyMotion1.0.0.tar EasyMotion1.0.0 && $(COMPRESS) EasyMotion1.0.0.tar) && $(MOVE) `dirname .obj/release-shared/EasyMotion1.0.0`/EasyMotion1.0.0.tar.gz . && $(DEL_FILE) -r .obj/release-shared/EasyMotion1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_copy2build_make_all: ../../../test/qt-creator-2.8.1-src/lib/qtcreator/plugins/XiaofengWu/EasyMotion.pluginspec
compiler_copy2build_clean:
	-$(DEL_FILE) ../../../test/qt-creator-2.8.1-src/lib/qtcreator/plugins/XiaofengWu/EasyMotion.pluginspec
../../../test/qt-creator-2.8.1-src/lib/qtcreator/plugins/XiaofengWu/EasyMotion.pluginspec: EasyMotion.pluginspec
	cp -f EasyMotion.pluginspec ../../../test/qt-creator-2.8.1-src/lib/qtcreator/plugins/XiaofengWu/EasyMotion.pluginspec

compiler_moc_header_make_all: .moc/release-shared/moc_easymotionplugin.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/release-shared/moc_easymotionplugin.cpp
.moc/release-shared/moc_easymotionplugin.cpp: easymotion_global.h \
		/usr/include/qt4/QtCore/QtGlobal \
		/usr/include/qt4/QtCore/qglobal.h \
		/usr/include/qt4/QtCore/qconfig.h \
		/usr/include/qt4/QtCore/qfeatures.h \
		../../../test/qt-creator-2.8.1-src/src/libs/extensionsystem/iplugin.h \
		../../../test/qt-creator-2.8.1-src/src/libs/extensionsystem/extensionsystem_global.h \
		/usr/include/qt4/QtCore/QObject \
		/usr/include/qt4/QtCore/qobject.h \
		/usr/include/qt4/QtCore/qobjectdefs.h \
		/usr/include/qt4/QtCore/qnamespace.h \
		/usr/include/qt4/QtCore/qstring.h \
		/usr/include/qt4/QtCore/qchar.h \
		/usr/include/qt4/QtCore/qbytearray.h \
		/usr/include/qt4/QtCore/qatomic.h \
		/usr/include/qt4/QtCore/qbasicatomic.h \
		/usr/include/qt4/QtCore/qatomic_bootstrap.h \
		/usr/include/qt4/QtCore/qatomic_arch.h \
		/usr/include/qt4/QtCore/qatomic_integrity.h \
		/usr/include/qt4/QtCore/qatomic_vxworks.h \
		/usr/include/qt4/QtCore/qatomic_powerpc.h \
		/usr/include/qt4/QtCore/qatomic_alpha.h \
		/usr/include/qt4/QtCore/qatomic_arm.h \
		/usr/include/qt4/QtCore/qatomic_armv7.h \
		/usr/include/qt4/QtCore/qatomic_armv6.h \
		/usr/include/qt4/QtCore/qatomic_armv5.h \
		/usr/include/qt4/QtCore/qatomic_avr32.h \
		/usr/include/qt4/QtCore/qatomic_bfin.h \
		/usr/include/qt4/QtCore/qatomic_generic.h \
		/usr/include/qt4/QtCore/qatomic_i386.h \
		/usr/include/qt4/QtCore/qatomic_ia64.h \
		/usr/include/qt4/QtCore/qatomic_macosx.h \
		/usr/include/qt4/QtCore/qatomic_x86_64.h \
		/usr/include/qt4/QtCore/qatomic_mips.h \
		/usr/include/qt4/QtCore/qatomic_parisc.h \
		/usr/include/qt4/QtCore/qatomic_s390.h \
		/usr/include/qt4/QtCore/qatomic_sparc.h \
		/usr/include/qt4/QtCore/qatomic_windows.h \
		/usr/include/qt4/QtCore/qatomic_windowsce.h \
		/usr/include/qt4/QtCore/qatomic_symbian.h \
		/usr/include/qt4/QtCore/qatomic_sh.h \
		/usr/include/qt4/QtCore/qatomic_sh4a.h \
		/usr/include/qt4/QtCore/qatomic_aarch64.h \
		/usr/include/qt4/Qt3Support/q3cstring.h \
		/usr/include/qt4/QtCore/qstringbuilder.h \
		/usr/include/qt4/QtCore/qmap.h \
		/usr/include/qt4/QtCore/qiterator.h \
		/usr/include/qt4/QtCore/qlist.h \
		/usr/include/qt4/QtCore/qalgorithms.h \
		/usr/include/qt4/QtCore/qcoreevent.h \
		/usr/include/qt4/QtCore/qscopedpointer.h \
		/usr/include/qt4/QtCore/QtPlugin \
		/usr/include/qt4/QtCore/qplugin.h \
		/usr/include/qt4/QtCore/qpointer.h \
		easymotionplugin.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) easymotionplugin.h -o .moc/release-shared/moc_easymotionplugin.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: .uic/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) .uic/qmake_image_collection.cpp
compiler_moc_source_make_all: .moc/release-shared/easymotionplugin.moc
compiler_moc_source_clean:
	-$(DEL_FILE) .moc/release-shared/easymotionplugin.moc
.moc/release-shared/easymotionplugin.moc: easymotionplugin.h \
		easymotion_global.h \
		/usr/include/qt4/QtCore/QtGlobal \
		/usr/include/qt4/QtCore/qglobal.h \
		/usr/include/qt4/QtCore/qconfig.h \
		/usr/include/qt4/QtCore/qfeatures.h \
		../../../test/qt-creator-2.8.1-src/src/libs/extensionsystem/iplugin.h \
		../../../test/qt-creator-2.8.1-src/src/libs/extensionsystem/extensionsystem_global.h \
		/usr/include/qt4/QtCore/QObject \
		/usr/include/qt4/QtCore/qobject.h \
		/usr/include/qt4/QtCore/qobjectdefs.h \
		/usr/include/qt4/QtCore/qnamespace.h \
		/usr/include/qt4/QtCore/qstring.h \
		/usr/include/qt4/QtCore/qchar.h \
		/usr/include/qt4/QtCore/qbytearray.h \
		/usr/include/qt4/QtCore/qatomic.h \
		/usr/include/qt4/QtCore/qbasicatomic.h \
		/usr/include/qt4/QtCore/qatomic_bootstrap.h \
		/usr/include/qt4/QtCore/qatomic_arch.h \
		/usr/include/qt4/QtCore/qatomic_integrity.h \
		/usr/include/qt4/QtCore/qatomic_vxworks.h \
		/usr/include/qt4/QtCore/qatomic_powerpc.h \
		/usr/include/qt4/QtCore/qatomic_alpha.h \
		/usr/include/qt4/QtCore/qatomic_arm.h \
		/usr/include/qt4/QtCore/qatomic_armv7.h \
		/usr/include/qt4/QtCore/qatomic_armv6.h \
		/usr/include/qt4/QtCore/qatomic_armv5.h \
		/usr/include/qt4/QtCore/qatomic_avr32.h \
		/usr/include/qt4/QtCore/qatomic_bfin.h \
		/usr/include/qt4/QtCore/qatomic_generic.h \
		/usr/include/qt4/QtCore/qatomic_i386.h \
		/usr/include/qt4/QtCore/qatomic_ia64.h \
		/usr/include/qt4/QtCore/qatomic_macosx.h \
		/usr/include/qt4/QtCore/qatomic_x86_64.h \
		/usr/include/qt4/QtCore/qatomic_mips.h \
		/usr/include/qt4/QtCore/qatomic_parisc.h \
		/usr/include/qt4/QtCore/qatomic_s390.h \
		/usr/include/qt4/QtCore/qatomic_sparc.h \
		/usr/include/qt4/QtCore/qatomic_windows.h \
		/usr/include/qt4/QtCore/qatomic_windowsce.h \
		/usr/include/qt4/QtCore/qatomic_symbian.h \
		/usr/include/qt4/QtCore/qatomic_sh.h \
		/usr/include/qt4/QtCore/qatomic_sh4a.h \
		/usr/include/qt4/QtCore/qatomic_aarch64.h \
		/usr/include/qt4/Qt3Support/q3cstring.h \
		/usr/include/qt4/QtCore/qstringbuilder.h \
		/usr/include/qt4/QtCore/qmap.h \
		/usr/include/qt4/QtCore/qiterator.h \
		/usr/include/qt4/QtCore/qlist.h \
		/usr/include/qt4/QtCore/qalgorithms.h \
		/usr/include/qt4/QtCore/qcoreevent.h \
		/usr/include/qt4/QtCore/qscopedpointer.h \
		/usr/include/qt4/QtCore/QtPlugin \
		/usr/include/qt4/QtCore/qplugin.h \
		/usr/include/qt4/QtCore/qpointer.h \
		easymotionconstants.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/icore.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/core_global.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/id.h \
		/usr/include/qt4/QtCore/QMetaType \
		/usr/include/qt4/QtCore/qmetatype.h \
		/usr/include/qt4/QtCore/qdatastream.h \
		/usr/include/qt4/QtCore/qiodevice.h \
		/usr/include/qt4/QtCore/QString \
		/usr/include/qt4/QtCore/QSettings \
		/usr/include/qt4/QtCore/qsettings.h \
		/usr/include/qt4/QtCore/qvariant.h \
		/usr/include/qt4/QtCore/qhash.h \
		/usr/include/qt4/QtCore/qpair.h \
		/usr/include/qt4/QtCore/qstringlist.h \
		/usr/include/qt4/QtCore/qregexp.h \
		/usr/include/qt4/QtCore/qstringmatcher.h \
		/usr/include/qt4/Qt3Support/q3valuelist.h \
		/usr/include/qt4/QtCore/qlinkedlist.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/icontext.h \
		/usr/include/qt4/QtCore/QList \
		/usr/include/qt4/QtCore/QPointer \
		/usr/include/qt4/QtGui/QWidget \
		/usr/include/qt4/QtGui/qwidget.h \
		/usr/include/qt4/QtGui/qwindowdefs.h \
		/usr/include/qt4/QtGui/qmacdefines_mac.h \
		/usr/include/qt4/QtGui/qwindowdefs_win.h \
		/usr/include/qt4/QtCore/qmargins.h \
		/usr/include/qt4/QtGui/qpaintdevice.h \
		/usr/include/qt4/QtCore/qrect.h \
		/usr/include/qt4/QtCore/qsize.h \
		/usr/include/qt4/QtCore/qpoint.h \
		/usr/include/qt4/QtGui/qpalette.h \
		/usr/include/qt4/QtGui/qcolor.h \
		/usr/include/qt4/QtGui/qrgb.h \
		/usr/include/qt4/QtGui/qbrush.h \
		/usr/include/qt4/QtCore/qvector.h \
		/usr/include/qt4/QtCore/QPointF \
		/usr/include/qt4/QtCore/QPoint \
		/usr/include/qt4/QtGui/qmatrix.h \
		/usr/include/qt4/QtGui/qpolygon.h \
		/usr/include/qt4/QtGui/qregion.h \
		/usr/include/qt4/QtCore/qline.h \
		/usr/include/qt4/QtGui/qwmatrix.h \
		/usr/include/qt4/QtGui/qtransform.h \
		/usr/include/qt4/QtGui/qpainterpath.h \
		/usr/include/qt4/QtGui/qimage.h \
		/usr/include/qt4/QtGui/qpixmap.h \
		/usr/include/qt4/QtCore/qsharedpointer.h \
		/usr/include/qt4/QtCore/qshareddata.h \
		/usr/include/qt4/QtCore/qsharedpointer_impl.h \
		/usr/include/qt4/QtGui/qfont.h \
		/usr/include/qt4/QtGui/qfontmetrics.h \
		/usr/include/qt4/QtGui/qfontinfo.h \
		/usr/include/qt4/QtGui/qsizepolicy.h \
		/usr/include/qt4/QtGui/qcursor.h \
		/usr/include/qt4/QtGui/qkeysequence.h \
		/usr/include/qt4/QtGui/qplatformwindowformat_qpa.h \
		/usr/include/qt4/QtGui/QPlatformWindow \
		/usr/include/qt4/QtGui/qplatformwindow_qpa.h \
		/usr/include/qt4/QtGui/qevent.h \
		/usr/include/qt4/QtGui/qmime.h \
		/usr/include/qt4/QtCore/qmimedata.h \
		/usr/include/qt4/QtGui/qdrag.h \
		/usr/include/qt4/QtCore/qset.h \
		/usr/include/qt4/QtCore/qfile.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/actionmanager/actionmanager.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/actionmanager/command.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/editormanager/editormanager.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/idocument.h \
		/usr/include/qt4/QtGui/QMenu \
		/usr/include/qt4/QtGui/qmenu.h \
		/usr/include/qt4/QtGui/qicon.h \
		/usr/include/qt4/QtGui/qaction.h \
		/usr/include/qt4/QtGui/qactiongroup.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/actionmanager/actioncontainer.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/coreconstants.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/texteditor/basetexteditor.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/texteditor/itexteditor.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/texteditor/texteditor_global.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/texteditor/itextmark.h \
		/usr/include/qt4/QtGui/QIcon \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/textdocument.h \
		../../../test/qt-creator-2.8.1-src/src/libs/utils/textfileformat.h \
		../../../test/qt-creator-2.8.1-src/src/libs/utils/utils_global.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/editormanager/ieditor.h \
		/usr/include/qt4/QtCore/QMap \
		../../../test/qt-creator-2.8.1-src/src/plugins/texteditor/codeassist/assistenums.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/find/ifindsupport.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/find/find_global.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/find/textfindconstants.h \
		/usr/include/qt4/QtCore/QFlags \
		/usr/include/qt4/QtGui/QTextDocument \
		/usr/include/qt4/QtGui/qtextdocument.h \
		/usr/include/qt4/QtGui/QPlainTextEdit \
		/usr/include/qt4/QtGui/qplaintextedit.h \
		/usr/include/qt4/QtGui/qtextedit.h \
		/usr/include/qt4/QtGui/qabstractscrollarea.h \
		/usr/include/qt4/QtGui/qframe.h \
		/usr/include/qt4/QtGui/qtextoption.h \
		/usr/include/qt4/QtGui/qtextcursor.h \
		/usr/include/qt4/QtGui/qtextformat.h \
		/usr/include/qt4/QtGui/qpen.h \
		/usr/include/qt4/QtGui/qtextobject.h \
		/usr/include/qt4/QtGui/qglyphrun.h \
		/usr/include/qt4/QtGui/qrawfont.h \
		/usr/include/qt4/QtGui/qfontdatabase.h \
		/usr/include/qt4/QtGui/qtextlayout.h \
		/usr/include/qt4/QtGui/qabstracttextdocumentlayout.h \
		/usr/include/qt4/QtCore/QSharedPointer \
		../../../test/qt-creator-2.8.1-src/src/libs/extensionsystem/pluginmanager.h \
		../../../test/qt-creator-2.8.1-src/src/libs/aggregation/aggregate.h \
		../../../test/qt-creator-2.8.1-src/src/libs/aggregation/aggregation_global.h \
		/usr/include/qt4/QtCore/QHash \
		/usr/include/qt4/QtCore/QReadWriteLock \
		/usr/include/qt4/QtCore/qreadwritelock.h \
		/usr/include/qt4/QtCore/QReadLocker \
		/usr/include/qt4/QtCore/QStringList \
		/usr/include/qt4/QtGui/QListWidget \
		/usr/include/qt4/QtGui/qlistwidget.h \
		/usr/include/qt4/QtGui/qlistview.h \
		/usr/include/qt4/QtGui/qabstractitemview.h \
		/usr/include/qt4/QtCore/qabstractitemmodel.h \
		/usr/include/qt4/QtGui/qitemselectionmodel.h \
		/usr/include/qt4/QtGui/qabstractitemdelegate.h \
		/usr/include/qt4/QtGui/qstyleoption.h \
		/usr/include/qt4/QtGui/qabstractspinbox.h \
		/usr/include/qt4/QtGui/qvalidator.h \
		/usr/include/qt4/QtCore/qlocale.h \
		/usr/include/qt4/QtGui/qslider.h \
		/usr/include/qt4/QtGui/qabstractslider.h \
		/usr/include/qt4/QtGui/qstyle.h \
		/usr/include/qt4/QtGui/qtabbar.h \
		/usr/include/qt4/QtGui/qtabwidget.h \
		/usr/include/qt4/QtGui/qrubberband.h \
		/usr/include/qt4/QtGui/QAction \
		/usr/include/qt4/QtGui/QMessageBox \
		/usr/include/qt4/QtGui/qmessagebox.h \
		/usr/include/qt4/QtGui/qdialog.h \
		/usr/include/qt4/QtGui/QMainWindow \
		/usr/include/qt4/QtGui/qmainwindow.h \
		/usr/include/qt4/QtGui/QApplication \
		/usr/include/qt4/QtGui/qapplication.h \
		/usr/include/qt4/QtCore/qcoreapplication.h \
		/usr/include/qt4/QtCore/qeventloop.h \
		/usr/include/qt4/QtGui/qdesktopwidget.h \
		/usr/include/qt4/QtGui/qtransportauth_qws.h \
		/usr/include/qt4/QtCore/qbuffer.h \
		/usr/include/qt4/QtCore/QDebug \
		/usr/include/qt4/QtCore/qdebug.h \
		/usr/include/qt4/QtCore/qtextstream.h \
		/usr/include/qt4/QtCore/qtextcodec.h \
		/usr/include/qt4/QtCore/qcontiguouscache.h \
		/usr/include/qt4/QtGui/QPainter \
		/usr/include/qt4/QtGui/qpainter.h \
		/usr/include/qt4/QtGui/qdrawutil.h \
		/usr/include/qt4/QtGui/QTextBlock \
		/usr/include/qt4/QtCore/QChar \
		/usr/include/qt4/QtCore/QPair \
		easymotionplugin.moc \
		easymotionplugin.cpp
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) easymotionplugin.cpp -o .moc/release-shared/easymotionplugin.moc

compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_copy2build_clean compiler_moc_header_clean compiler_moc_source_clean 

####### Compile

.obj/release-shared/easymotionplugin.o: easymotionplugin.cpp easymotionplugin.h \
		easymotion_global.h \
		/usr/include/qt4/QtCore/QtGlobal \
		/usr/include/qt4/QtCore/qglobal.h \
		/usr/include/qt4/QtCore/qconfig.h \
		/usr/include/qt4/QtCore/qfeatures.h \
		../../../test/qt-creator-2.8.1-src/src/libs/extensionsystem/iplugin.h \
		../../../test/qt-creator-2.8.1-src/src/libs/extensionsystem/extensionsystem_global.h \
		/usr/include/qt4/QtCore/QObject \
		/usr/include/qt4/QtCore/qobject.h \
		/usr/include/qt4/QtCore/qobjectdefs.h \
		/usr/include/qt4/QtCore/qnamespace.h \
		/usr/include/qt4/QtCore/qstring.h \
		/usr/include/qt4/QtCore/qchar.h \
		/usr/include/qt4/QtCore/qbytearray.h \
		/usr/include/qt4/QtCore/qatomic.h \
		/usr/include/qt4/QtCore/qbasicatomic.h \
		/usr/include/qt4/QtCore/qatomic_bootstrap.h \
		/usr/include/qt4/QtCore/qatomic_arch.h \
		/usr/include/qt4/QtCore/qatomic_integrity.h \
		/usr/include/qt4/QtCore/qatomic_vxworks.h \
		/usr/include/qt4/QtCore/qatomic_powerpc.h \
		/usr/include/qt4/QtCore/qatomic_alpha.h \
		/usr/include/qt4/QtCore/qatomic_arm.h \
		/usr/include/qt4/QtCore/qatomic_armv7.h \
		/usr/include/qt4/QtCore/qatomic_armv6.h \
		/usr/include/qt4/QtCore/qatomic_armv5.h \
		/usr/include/qt4/QtCore/qatomic_avr32.h \
		/usr/include/qt4/QtCore/qatomic_bfin.h \
		/usr/include/qt4/QtCore/qatomic_generic.h \
		/usr/include/qt4/QtCore/qatomic_i386.h \
		/usr/include/qt4/QtCore/qatomic_ia64.h \
		/usr/include/qt4/QtCore/qatomic_macosx.h \
		/usr/include/qt4/QtCore/qatomic_x86_64.h \
		/usr/include/qt4/QtCore/qatomic_mips.h \
		/usr/include/qt4/QtCore/qatomic_parisc.h \
		/usr/include/qt4/QtCore/qatomic_s390.h \
		/usr/include/qt4/QtCore/qatomic_sparc.h \
		/usr/include/qt4/QtCore/qatomic_windows.h \
		/usr/include/qt4/QtCore/qatomic_windowsce.h \
		/usr/include/qt4/QtCore/qatomic_symbian.h \
		/usr/include/qt4/QtCore/qatomic_sh.h \
		/usr/include/qt4/QtCore/qatomic_sh4a.h \
		/usr/include/qt4/QtCore/qatomic_aarch64.h \
		/usr/include/qt4/Qt3Support/q3cstring.h \
		/usr/include/qt4/QtCore/qstringbuilder.h \
		/usr/include/qt4/QtCore/qmap.h \
		/usr/include/qt4/QtCore/qiterator.h \
		/usr/include/qt4/QtCore/qlist.h \
		/usr/include/qt4/QtCore/qalgorithms.h \
		/usr/include/qt4/QtCore/qcoreevent.h \
		/usr/include/qt4/QtCore/qscopedpointer.h \
		/usr/include/qt4/QtCore/QtPlugin \
		/usr/include/qt4/QtCore/qplugin.h \
		/usr/include/qt4/QtCore/qpointer.h \
		easymotionconstants.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/icore.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/core_global.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/id.h \
		/usr/include/qt4/QtCore/QMetaType \
		/usr/include/qt4/QtCore/qmetatype.h \
		/usr/include/qt4/QtCore/qdatastream.h \
		/usr/include/qt4/QtCore/qiodevice.h \
		/usr/include/qt4/QtCore/QString \
		/usr/include/qt4/QtCore/QSettings \
		/usr/include/qt4/QtCore/qsettings.h \
		/usr/include/qt4/QtCore/qvariant.h \
		/usr/include/qt4/QtCore/qhash.h \
		/usr/include/qt4/QtCore/qpair.h \
		/usr/include/qt4/QtCore/qstringlist.h \
		/usr/include/qt4/QtCore/qregexp.h \
		/usr/include/qt4/QtCore/qstringmatcher.h \
		/usr/include/qt4/Qt3Support/q3valuelist.h \
		/usr/include/qt4/QtCore/qlinkedlist.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/icontext.h \
		/usr/include/qt4/QtCore/QList \
		/usr/include/qt4/QtCore/QPointer \
		/usr/include/qt4/QtGui/QWidget \
		/usr/include/qt4/QtGui/qwidget.h \
		/usr/include/qt4/QtGui/qwindowdefs.h \
		/usr/include/qt4/QtGui/qmacdefines_mac.h \
		/usr/include/qt4/QtGui/qwindowdefs_win.h \
		/usr/include/qt4/QtCore/qmargins.h \
		/usr/include/qt4/QtGui/qpaintdevice.h \
		/usr/include/qt4/QtCore/qrect.h \
		/usr/include/qt4/QtCore/qsize.h \
		/usr/include/qt4/QtCore/qpoint.h \
		/usr/include/qt4/QtGui/qpalette.h \
		/usr/include/qt4/QtGui/qcolor.h \
		/usr/include/qt4/QtGui/qrgb.h \
		/usr/include/qt4/QtGui/qbrush.h \
		/usr/include/qt4/QtCore/qvector.h \
		/usr/include/qt4/QtCore/QPointF \
		/usr/include/qt4/QtCore/QPoint \
		/usr/include/qt4/QtGui/qmatrix.h \
		/usr/include/qt4/QtGui/qpolygon.h \
		/usr/include/qt4/QtGui/qregion.h \
		/usr/include/qt4/QtCore/qline.h \
		/usr/include/qt4/QtGui/qwmatrix.h \
		/usr/include/qt4/QtGui/qtransform.h \
		/usr/include/qt4/QtGui/qpainterpath.h \
		/usr/include/qt4/QtGui/qimage.h \
		/usr/include/qt4/QtGui/qpixmap.h \
		/usr/include/qt4/QtCore/qsharedpointer.h \
		/usr/include/qt4/QtCore/qshareddata.h \
		/usr/include/qt4/QtCore/qsharedpointer_impl.h \
		/usr/include/qt4/QtGui/qfont.h \
		/usr/include/qt4/QtGui/qfontmetrics.h \
		/usr/include/qt4/QtGui/qfontinfo.h \
		/usr/include/qt4/QtGui/qsizepolicy.h \
		/usr/include/qt4/QtGui/qcursor.h \
		/usr/include/qt4/QtGui/qkeysequence.h \
		/usr/include/qt4/QtGui/qplatformwindowformat_qpa.h \
		/usr/include/qt4/QtGui/QPlatformWindow \
		/usr/include/qt4/QtGui/qplatformwindow_qpa.h \
		/usr/include/qt4/QtGui/qevent.h \
		/usr/include/qt4/QtGui/qmime.h \
		/usr/include/qt4/QtCore/qmimedata.h \
		/usr/include/qt4/QtGui/qdrag.h \
		/usr/include/qt4/QtCore/qset.h \
		/usr/include/qt4/QtCore/qfile.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/actionmanager/actionmanager.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/actionmanager/command.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/editormanager/editormanager.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/idocument.h \
		/usr/include/qt4/QtGui/QMenu \
		/usr/include/qt4/QtGui/qmenu.h \
		/usr/include/qt4/QtGui/qicon.h \
		/usr/include/qt4/QtGui/qaction.h \
		/usr/include/qt4/QtGui/qactiongroup.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/actionmanager/actioncontainer.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/coreconstants.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/texteditor/basetexteditor.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/texteditor/itexteditor.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/texteditor/texteditor_global.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/texteditor/itextmark.h \
		/usr/include/qt4/QtGui/QIcon \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/textdocument.h \
		../../../test/qt-creator-2.8.1-src/src/libs/utils/textfileformat.h \
		../../../test/qt-creator-2.8.1-src/src/libs/utils/utils_global.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/coreplugin/editormanager/ieditor.h \
		/usr/include/qt4/QtCore/QMap \
		../../../test/qt-creator-2.8.1-src/src/plugins/texteditor/codeassist/assistenums.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/find/ifindsupport.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/find/find_global.h \
		../../../test/qt-creator-2.8.1-src/src/plugins/find/textfindconstants.h \
		/usr/include/qt4/QtCore/QFlags \
		/usr/include/qt4/QtGui/QTextDocument \
		/usr/include/qt4/QtGui/qtextdocument.h \
		/usr/include/qt4/QtGui/QPlainTextEdit \
		/usr/include/qt4/QtGui/qplaintextedit.h \
		/usr/include/qt4/QtGui/qtextedit.h \
		/usr/include/qt4/QtGui/qabstractscrollarea.h \
		/usr/include/qt4/QtGui/qframe.h \
		/usr/include/qt4/QtGui/qtextoption.h \
		/usr/include/qt4/QtGui/qtextcursor.h \
		/usr/include/qt4/QtGui/qtextformat.h \
		/usr/include/qt4/QtGui/qpen.h \
		/usr/include/qt4/QtGui/qtextobject.h \
		/usr/include/qt4/QtGui/qglyphrun.h \
		/usr/include/qt4/QtGui/qrawfont.h \
		/usr/include/qt4/QtGui/qfontdatabase.h \
		/usr/include/qt4/QtGui/qtextlayout.h \
		/usr/include/qt4/QtGui/qabstracttextdocumentlayout.h \
		/usr/include/qt4/QtCore/QSharedPointer \
		../../../test/qt-creator-2.8.1-src/src/libs/extensionsystem/pluginmanager.h \
		../../../test/qt-creator-2.8.1-src/src/libs/aggregation/aggregate.h \
		../../../test/qt-creator-2.8.1-src/src/libs/aggregation/aggregation_global.h \
		/usr/include/qt4/QtCore/QHash \
		/usr/include/qt4/QtCore/QReadWriteLock \
		/usr/include/qt4/QtCore/qreadwritelock.h \
		/usr/include/qt4/QtCore/QReadLocker \
		/usr/include/qt4/QtCore/QStringList \
		/usr/include/qt4/QtGui/QListWidget \
		/usr/include/qt4/QtGui/qlistwidget.h \
		/usr/include/qt4/QtGui/qlistview.h \
		/usr/include/qt4/QtGui/qabstractitemview.h \
		/usr/include/qt4/QtCore/qabstractitemmodel.h \
		/usr/include/qt4/QtGui/qitemselectionmodel.h \
		/usr/include/qt4/QtGui/qabstractitemdelegate.h \
		/usr/include/qt4/QtGui/qstyleoption.h \
		/usr/include/qt4/QtGui/qabstractspinbox.h \
		/usr/include/qt4/QtGui/qvalidator.h \
		/usr/include/qt4/QtCore/qlocale.h \
		/usr/include/qt4/QtGui/qslider.h \
		/usr/include/qt4/QtGui/qabstractslider.h \
		/usr/include/qt4/QtGui/qstyle.h \
		/usr/include/qt4/QtGui/qtabbar.h \
		/usr/include/qt4/QtGui/qtabwidget.h \
		/usr/include/qt4/QtGui/qrubberband.h \
		/usr/include/qt4/QtGui/QAction \
		/usr/include/qt4/QtGui/QMessageBox \
		/usr/include/qt4/QtGui/qmessagebox.h \
		/usr/include/qt4/QtGui/qdialog.h \
		/usr/include/qt4/QtGui/QMainWindow \
		/usr/include/qt4/QtGui/qmainwindow.h \
		/usr/include/qt4/QtGui/QApplication \
		/usr/include/qt4/QtGui/qapplication.h \
		/usr/include/qt4/QtCore/qcoreapplication.h \
		/usr/include/qt4/QtCore/qeventloop.h \
		/usr/include/qt4/QtGui/qdesktopwidget.h \
		/usr/include/qt4/QtGui/qtransportauth_qws.h \
		/usr/include/qt4/QtCore/qbuffer.h \
		/usr/include/qt4/QtCore/QDebug \
		/usr/include/qt4/QtCore/qdebug.h \
		/usr/include/qt4/QtCore/qtextstream.h \
		/usr/include/qt4/QtCore/qtextcodec.h \
		/usr/include/qt4/QtCore/qcontiguouscache.h \
		/usr/include/qt4/QtGui/QPainter \
		/usr/include/qt4/QtGui/qpainter.h \
		/usr/include/qt4/QtGui/qdrawutil.h \
		/usr/include/qt4/QtGui/QTextBlock \
		/usr/include/qt4/QtCore/QChar \
		/usr/include/qt4/QtCore/QPair \
		easymotionplugin.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/easymotionplugin.o easymotionplugin.cpp

.obj/release-shared/moc_easymotionplugin.o: .moc/release-shared/moc_easymotionplugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/moc_easymotionplugin.o .moc/release-shared/moc_easymotionplugin.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/lib/qtcreator/plugins/XiaofengWu/ || $(MKDIR) $(INSTALL_ROOT)/lib/qtcreator/plugins/XiaofengWu/ 
	-$(INSTALL_PROGRAM) "../../../test/qt-creator-2.8.1-src/lib/qtcreator/plugins/XiaofengWu/$(TARGET)" "$(INSTALL_ROOT)/lib/qtcreator/plugins/XiaofengWu/$(TARGET)"
	-$(STRIP) --strip-unneeded "$(INSTALL_ROOT)/lib/qtcreator/plugins/XiaofengWu/$(TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/lib/qtcreator/plugins/XiaofengWu/$(TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/lib/qtcreator/plugins/XiaofengWu/ 


install_pluginspec: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/lib/qtcreator/plugins/XiaofengWu/ || $(MKDIR) $(INSTALL_ROOT)/lib/qtcreator/plugins/XiaofengWu/ 
	-$(INSTALL_FILE) /home/xwu/Dropbox/test/EasyMotion/EasyMotion.pluginspec $(INSTALL_ROOT)/lib/qtcreator/plugins/XiaofengWu/


uninstall_pluginspec:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/lib/qtcreator/plugins/XiaofengWu/EasyMotion.pluginspec
	-$(DEL_DIR) $(INSTALL_ROOT)/lib/qtcreator/plugins/XiaofengWu/ 


install:  install_target install_pluginspec  FORCE

uninstall: uninstall_target uninstall_pluginspec   FORCE

FORCE:

