#############################################################################
# Makefile for building: libEasyMotion.dylib
# Generated by qmake (3.0) (Qt 5.1.1) on: Mon Feb 17 19:15:56 2014
# Project:  EasyMotion.pro
# Template: lib
# Command: /usr/bin/qmake -o Makefile EasyMotion.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DEASYMOTION_LIBRARY -DIDE_LIBRARY_BASENAME=\"lib\" -DQT_CREATOR -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_DISABLE_DEPRECATED_BEFORE=0x040900 -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_CONCURRENT_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -fvisibility=hidden -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -fPIC $(DEFINES)
INCPATH       = -I../../../Qt5.1.1/5.1.1/clang_64/mkspecs/macx-clang -I. -I../../../tmp/qtcreator-3.0/src -I../../../tmp/qtcreator-3.0/src/libs -I/Users/dj/tmp/qtcreator-3.0/tools -I../../../tmp/qtcreator-3.0/src/plugins -I../../../Qt5.1.1/5.1.1/clang_64/include -I../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets -I../../../Qt5.1.1/5.1.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../../Qt5.1.1/5.1.1/clang_64/include/QtConcurrent -I../../../Qt5.1.1/5.1.1/clang_64/lib/QtConcurrent.framework/Versions/5/Headers -I../../../Qt5.1.1/5.1.1/clang_64/include/QtGui -I../../../Qt5.1.1/5.1.1/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../../Qt5.1.1/5.1.1/clang_64/include/QtCore -I../../../Qt5.1.1/5.1.1/clang_64/lib/QtCore.framework/Versions/5/Headers -I.moc/release-shared -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -F/Users/dj/Qt5.1.1/5.1.1/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-rpath,@loader_path/../../,-rpath,@executable_path/../ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -single_module -dynamiclib -Wl,-install_name,@rpath/PlugIns/XiaofengWu/libEasyMotion.dylib
LIBS          = $(SUBLIBS) -F/Users/dj/Qt5.1.1/5.1.1/clang_64/lib -L/Users/dj/tmp/qtcreator-3.0/bin/Qt\ Creator.app/Contents/PlugIns -lCore -lExtensionSystem -lUtils -lAggregation -L/Users/dj/tmp/qtcreator-3.0/bin/Qt\ Creator.app/Contents/PlugIns/QtProject -L/Users/dj/tmp/qtcreator-3.0/bin/Qt\ Creator.app/Contents/PlugIns/XiaofengWu -framework QtWidgets -framework QtGui -framework QtCore -framework QtConcurrent -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = .obj/release-shared/

####### Files

SOURCES       = easymotionplugin.cpp .moc/release-shared/moc_easymotionplugin.cpp
OBJECTS       = .obj/release-shared/easymotionplugin.o \
		.obj/release-shared/moc_easymotionplugin.o
DIST          = ../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/qdevice.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/device_config.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/shell-unix.conf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/unix.conf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/mac.conf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/macx.conf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/clang.conf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/qconfig.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_v8.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/unix/default_pre.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/default_pre.prf \
		EasyMotion_dependencies.pri \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/coreplugin_dependencies.pri \
		../../../tmp/qtcreator-3.0/src/libs/extensionsystem/extensionsystem_dependencies.pri \
		../../../tmp/qtcreator-3.0/src/libs/utils/utils_dependencies.pri \
		../../../tmp/qtcreator-3.0/src/libs/aggregation/aggregation_dependencies.pri \
		../../../tmp/qtcreator-3.0/qtcreator.pri \
		../../../tmp/qtcreator-3.0/src/qtcreatorplugin.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/default_post.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/unix/hide_symbols.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/qt.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/resources.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/moc.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/uic.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/yacc.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/lex.prf \
		easymotion.pro \
		EasyMotion.pluginspec.in \
		EasyMotion.pro
QMAKE_TARGET  = EasyMotion
DESTDIR       = ../../../tmp/qtcreator-3.0/bin/Qt Creator.app/Contents/PlugIns/XiaofengWu/#avoid trailing-slash linebreak
TARGET        = libEasyMotion.dylib
TARGETD       = libEasyMotion.dylib

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-mmacosx-version-min=10.6 \
		-fvisibility=hidden \
		-fvisibility-inlines-hidden \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  ../../../tmp/qtcreator-3.0/bin/Qt\ Creator.app/Contents/PlugIns/XiaofengWu/$(TARGET)

../../../tmp/qtcreator-3.0/bin/Qt\ Creator.app/Contents/PlugIns/XiaofengWu/$(TARGET): ../../../tmp/qtcreator-3.0/bin/Qt\ Creator.app/Contents/PlugIns/XiaofengWu/EasyMotion.pluginspec $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@test -d ../../../tmp/qtcreator-3.0/bin/Qt\ Creator.app/Contents/PlugIns/XiaofengWu/ || mkdir -p ../../../tmp/qtcreator-3.0/bin/Qt\ Creator.app/Contents/PlugIns/XiaofengWu/
	-$(DEL_FILE) $(TARGET)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-$(MOVE) $(TARGET) ../../../tmp/qtcreator-3.0/bin/Qt\ Creator.app/Contents/PlugIns/XiaofengWu/ 



Makefile: EasyMotion.pro ../../../Qt5.1.1/5.1.1/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/qdevice.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/device_config.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/shell-unix.conf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/unix.conf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/mac.conf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/macx.conf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/clang.conf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/qconfig.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_v8.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/unix/default_pre.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/default_pre.prf \
		EasyMotion_dependencies.pri \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/coreplugin_dependencies.pri \
		../../../tmp/qtcreator-3.0/src/libs/extensionsystem/extensionsystem_dependencies.pri \
		../../../tmp/qtcreator-3.0/src/libs/utils/utils_dependencies.pri \
		../../../tmp/qtcreator-3.0/src/libs/aggregation/aggregation_dependencies.pri \
		../../../tmp/qtcreator-3.0/qtcreator.pri \
		../../../tmp/qtcreator-3.0/src/qtcreatorplugin.pri \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/default_post.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/unix/hide_symbols.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/qt.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/resources.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/moc.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/uic.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/yacc.prf \
		../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/lex.prf \
		easymotion.pro \
		EasyMotion.pluginspec.in \
		/Users/dj/Qt5.1.1/5.1.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/dj/Qt5.1.1/5.1.1/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/dj/Qt5.1.1/5.1.1/clang_64/lib/QtCore.framework/QtCore.prl \
		/Users/dj/Qt5.1.1/5.1.1/clang_64/lib/QtConcurrent.framework/QtConcurrent.prl
	$(QMAKE) -o Makefile EasyMotion.pro
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/qdevice.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/device_config.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/shell-unix.conf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/unix.conf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/mac.conf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/macx.conf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/clang.conf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/qconfig.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_clucene.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_v8.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/qt_config.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/spec_post.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/default_pre.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/unix/default_pre.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/default_pre.prf:
EasyMotion_dependencies.pri:
../../../tmp/qtcreator-3.0/src/plugins/coreplugin/coreplugin_dependencies.pri:
../../../tmp/qtcreator-3.0/src/libs/extensionsystem/extensionsystem_dependencies.pri:
../../../tmp/qtcreator-3.0/src/libs/utils/utils_dependencies.pri:
../../../tmp/qtcreator-3.0/src/libs/aggregation/aggregation_dependencies.pri:
../../../tmp/qtcreator-3.0/qtcreator.pri:
../../../tmp/qtcreator-3.0/src/qtcreatorplugin.pri:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/default_post.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/unix/hide_symbols.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/warn_on.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/qt.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/resources.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/moc.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/uic.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/exceptions.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/yacc.prf:
../../../Qt5.1.1/5.1.1/clang_64/mkspecs/features/lex.prf:
easymotion.pro:
EasyMotion.pluginspec.in:
/Users/dj/Qt5.1.1/5.1.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/dj/Qt5.1.1/5.1.1/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/dj/Qt5.1.1/5.1.1/clang_64/lib/QtCore.framework/QtCore.prl:
/Users/dj/Qt5.1.1/5.1.1/clang_64/lib/QtConcurrent.framework/QtConcurrent.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile EasyMotion.pro

qmake_all: FORCE

dist: 
	@test -d .obj/release-shared/EasyMotion1.0.0 || mkdir -p .obj/release-shared/EasyMotion1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .obj/release-shared/EasyMotion1.0.0/ && $(COPY_FILE) --parents EasyMotion.pluginspec .obj/release-shared/EasyMotion1.0.0/ && $(COPY_FILE) --parents EasyMotion.pluginspec .obj/release-shared/EasyMotion1.0.0/ && $(COPY_FILE) --parents easymotionplugin.h easymotion_global.h easymotionconstants.h .obj/release-shared/EasyMotion1.0.0/ && $(COPY_FILE) --parents easymotionplugin.cpp .obj/release-shared/EasyMotion1.0.0/ && (cd `dirname .obj/release-shared/EasyMotion1.0.0` && $(TAR) EasyMotion1.0.0.tar EasyMotion1.0.0 && $(COMPRESS) EasyMotion1.0.0.tar) && $(MOVE) `dirname .obj/release-shared/EasyMotion1.0.0`/EasyMotion1.0.0.tar.gz . && $(DEL_FILE) -r .obj/release-shared/EasyMotion1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_copy2build_make_all: ../../../tmp/qtcreator-3.0/bin/Qt\ Creator.app/Contents/PlugIns/XiaofengWu/EasyMotion.pluginspec
../../../tmp/qtcreator-3.0/bin/Qt\ Creator.app/Contents/PlugIns/XiaofengWu/EasyMotion.pluginspec: EasyMotion.pluginspec
	cp -f EasyMotion.pluginspec ../../../tmp/qtcreator-3.0/bin/Qt\ Creator.app/Contents/PlugIns/XiaofengWu/EasyMotion.pluginspec

compiler_pluginspec2json_make_all: EasyMotion.json
compiler_pluginspec2json_clean:
	-$(DEL_FILE) EasyMotion.json
EasyMotion.json: EasyMotion.pluginspec
	/Users/dj/Qt5.1.1/5.1.1/clang_64/bin/xmlpatterns -no-format -output EasyMotion.json /Users/dj/tmp/qtcreator-3.0/src/pluginjsonmetadata.xsl /Users/dj/Dropbox/test/EasyMotion/EasyMotion.pluginspec

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: .moc/release-shared/moc_easymotionplugin.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/release-shared/moc_easymotionplugin.cpp
.moc/release-shared/moc_easymotionplugin.cpp: easymotion_global.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QtGlobal \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qglobal.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qconfig.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qfeatures.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qsystemdetection.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qcompilerdetection.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qprocessordetection.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qglobalstatic.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qbasicatomic.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qgenericatomic.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_msvc.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_integrity.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qoldbasicatomic.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_vxworks.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_power.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_alpha.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_armv7.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_armv6.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_armv5.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_bfin.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_ia64.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_mips.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_s390.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_sh4a.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_sparc.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_x86.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_gcc.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_unix.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qmutex.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qlogging.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qflags.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qtypeinfo.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qtypetraits.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qsysinfo.h \
		../../../tmp/qtcreator-3.0/src/libs/extensionsystem/iplugin.h \
		../../../tmp/qtcreator-3.0/src/libs/extensionsystem/extensionsystem_global.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QObject \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qobject.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qobjectdefs.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qnamespace.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qstring.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qchar.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qbytearray.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qrefcount.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qarraydata.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qstringbuilder.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qlist.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qalgorithms.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qiterator.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qcoreevent.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qscopedpointer.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qmetatype.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qvarlengtharray.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qcontainerfwd.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qisenum.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qobject_impl.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QtPlugin \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qplugin.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qpointer.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qsharedpointer.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qshareddata.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qhash.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qpair.h \
		easymotionplugin.h \
		EasyMotion.json
	/Users/dj/Qt5.1.1/5.1.1/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) easymotionplugin.h -o .moc/release-shared/moc_easymotionplugin.cpp

compiler_moc_source_make_all: .moc/release-shared/easymotionplugin.moc
compiler_moc_source_clean:
	-$(DEL_FILE) .moc/release-shared/easymotionplugin.moc
.moc/release-shared/easymotionplugin.moc: easymotionplugin.h \
		easymotion_global.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QtGlobal \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qglobal.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qconfig.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qfeatures.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qsystemdetection.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qcompilerdetection.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qprocessordetection.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qglobalstatic.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qbasicatomic.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qgenericatomic.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_msvc.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_integrity.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qoldbasicatomic.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_vxworks.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_power.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_alpha.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_armv7.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_armv6.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_armv5.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_bfin.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_ia64.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_mips.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_s390.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_sh4a.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_sparc.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_x86.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_gcc.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_unix.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qmutex.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qlogging.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qflags.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qtypeinfo.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qtypetraits.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qsysinfo.h \
		../../../tmp/qtcreator-3.0/src/libs/extensionsystem/iplugin.h \
		../../../tmp/qtcreator-3.0/src/libs/extensionsystem/extensionsystem_global.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QObject \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qobject.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qobjectdefs.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qnamespace.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qstring.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qchar.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qbytearray.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qrefcount.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qarraydata.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qstringbuilder.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qlist.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qalgorithms.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qiterator.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qcoreevent.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qscopedpointer.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qmetatype.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qvarlengtharray.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qcontainerfwd.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qisenum.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qobject_impl.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QtPlugin \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qplugin.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qpointer.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qsharedpointer.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qshareddata.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qhash.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qpair.h \
		easymotionconstants.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/icore.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/core_global.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/id.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QMetaType \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QString \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QSettings \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qsettings.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qvariant.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qmap.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qdebug.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qtextstream.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qiodevice.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qlocale.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qvector.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qpoint.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qset.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qcontiguouscache.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/icontext.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QList \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QPointer \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/QWidget \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qwidget.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qwindowdefs.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qmargins.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qrect.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qsize.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qpaintdevice.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qpalette.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qcolor.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qrgb.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qstringlist.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qdatastream.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qregexp.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qstringmatcher.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qbrush.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qmatrix.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qpolygon.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qregion.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qline.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qtransform.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qpainterpath.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qimage.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qpixmap.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qfont.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qfontmetrics.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qfontinfo.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qsizepolicy.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qcursor.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qkeysequence.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qevent.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qurl.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qurlquery.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qfile.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qfiledevice.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qvector2d.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qtouchdevice.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/actionmanager/actionmanager.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/actionmanager/command.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/editormanager/editormanager.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/editormanager/documentmodel.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QAbstractItemModel \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qabstractitemmodel.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/idocument.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/QMenu \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qmenu.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qicon.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qaction.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qactiongroup.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/actionmanager/actioncontainer.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/coreconstants.h \
		../../../tmp/qtcreator-3.0/src/plugins/texteditor/basetexteditor.h \
		../../../tmp/qtcreator-3.0/src/plugins/texteditor/itexteditor.h \
		../../../tmp/qtcreator-3.0/src/plugins/texteditor/texteditor_global.h \
		../../../tmp/qtcreator-3.0/src/plugins/texteditor/itextmark.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/QIcon \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/textdocument.h \
		../../../tmp/qtcreator-3.0/src/libs/utils/textfileformat.h \
		../../../tmp/qtcreator-3.0/src/libs/utils/utils_global.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/editormanager/ieditor.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QMap \
		../../../tmp/qtcreator-3.0/src/plugins/texteditor/codeassist/assistenums.h \
		../../../tmp/qtcreator-3.0/src/plugins/find/ifindsupport.h \
		../../../tmp/qtcreator-3.0/src/plugins/find/find_global.h \
		../../../tmp/qtcreator-3.0/src/plugins/find/textfindconstants.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QFlags \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/QTextDocument \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qtextdocument.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/QPlainTextEdit \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qplaintextedit.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qtextedit.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qabstractscrollarea.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qframe.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qtextoption.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qtextcursor.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qtextformat.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qpen.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qabstracttextdocumentlayout.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qtextlayout.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qglyphrun.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qrawfont.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qfontdatabase.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QSharedPointer \
		../../../tmp/qtcreator-3.0/src/libs/extensionsystem/pluginmanager.h \
		../../../tmp/qtcreator-3.0/src/libs/aggregation/aggregate.h \
		../../../tmp/qtcreator-3.0/src/libs/aggregation/aggregation_global.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QHash \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QReadWriteLock \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qreadwritelock.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QReadLocker \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QStringList \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/QListWidget \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qlistwidget.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qlistview.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qabstractitemview.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qitemselectionmodel.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qabstractitemdelegate.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qstyleoption.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qabstractspinbox.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qvalidator.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qregularexpression.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qslider.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qabstractslider.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qstyle.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qtabbar.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qtabwidget.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qrubberband.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/QAction \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/QMessageBox \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qmessagebox.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qdialog.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/QMainWindow \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qmainwindow.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/QApplication \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qapplication.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qcoreapplication.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qeventloop.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qdesktopwidget.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qguiapplication.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qinputmethod.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QDebug \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/QPainter \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qpainter.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/QTextBlock \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qtextobject.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QChar \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QPair \
		easymotionplugin.cpp
	/Users/dj/Qt5.1.1/5.1.1/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) easymotionplugin.cpp -o .moc/release-shared/easymotionplugin.moc

compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_pluginspec2json_clean compiler_moc_header_clean compiler_moc_source_clean 

####### Compile

.obj/release-shared/easymotionplugin.o: easymotionplugin.cpp easymotionplugin.h \
		easymotion_global.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QtGlobal \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qglobal.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qconfig.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qfeatures.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qsystemdetection.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qcompilerdetection.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qprocessordetection.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qglobalstatic.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qbasicatomic.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qgenericatomic.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_msvc.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_integrity.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qoldbasicatomic.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_vxworks.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_power.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_alpha.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_armv7.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_armv6.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_armv5.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_bfin.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_ia64.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_mips.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_s390.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_sh4a.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_sparc.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_x86.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_gcc.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qatomic_unix.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qmutex.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qlogging.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qflags.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qtypeinfo.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qtypetraits.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qsysinfo.h \
		../../../tmp/qtcreator-3.0/src/libs/extensionsystem/iplugin.h \
		../../../tmp/qtcreator-3.0/src/libs/extensionsystem/extensionsystem_global.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QObject \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qobject.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qobjectdefs.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qnamespace.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qstring.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qchar.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qbytearray.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qrefcount.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qarraydata.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qstringbuilder.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qlist.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qalgorithms.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qiterator.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qcoreevent.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qscopedpointer.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qmetatype.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qvarlengtharray.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qcontainerfwd.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qisenum.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qobject_impl.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QtPlugin \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qplugin.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qpointer.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qsharedpointer.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qshareddata.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qhash.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qpair.h \
		easymotionconstants.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/icore.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/core_global.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/id.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QMetaType \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QString \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QSettings \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qsettings.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qvariant.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qmap.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qdebug.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qtextstream.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qiodevice.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qlocale.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qvector.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qpoint.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qset.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qcontiguouscache.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/icontext.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QList \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QPointer \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/QWidget \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qwidget.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qwindowdefs.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qmargins.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qrect.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qsize.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qpaintdevice.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qpalette.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qcolor.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qrgb.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qstringlist.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qdatastream.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qregexp.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qstringmatcher.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qbrush.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qmatrix.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qpolygon.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qregion.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qline.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qtransform.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qpainterpath.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qimage.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qpixmap.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qfont.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qfontmetrics.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qfontinfo.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qsizepolicy.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qcursor.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qkeysequence.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qevent.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qurl.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qurlquery.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qfile.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qfiledevice.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qvector2d.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qtouchdevice.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/actionmanager/actionmanager.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/actionmanager/command.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/editormanager/editormanager.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/editormanager/documentmodel.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QAbstractItemModel \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qabstractitemmodel.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/idocument.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/QMenu \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qmenu.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qicon.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qaction.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qactiongroup.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/actionmanager/actioncontainer.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/coreconstants.h \
		../../../tmp/qtcreator-3.0/src/plugins/texteditor/basetexteditor.h \
		../../../tmp/qtcreator-3.0/src/plugins/texteditor/itexteditor.h \
		../../../tmp/qtcreator-3.0/src/plugins/texteditor/texteditor_global.h \
		../../../tmp/qtcreator-3.0/src/plugins/texteditor/itextmark.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/QIcon \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/textdocument.h \
		../../../tmp/qtcreator-3.0/src/libs/utils/textfileformat.h \
		../../../tmp/qtcreator-3.0/src/libs/utils/utils_global.h \
		../../../tmp/qtcreator-3.0/src/plugins/coreplugin/editormanager/ieditor.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QMap \
		../../../tmp/qtcreator-3.0/src/plugins/texteditor/codeassist/assistenums.h \
		../../../tmp/qtcreator-3.0/src/plugins/find/ifindsupport.h \
		../../../tmp/qtcreator-3.0/src/plugins/find/find_global.h \
		../../../tmp/qtcreator-3.0/src/plugins/find/textfindconstants.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QFlags \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/QTextDocument \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qtextdocument.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/QPlainTextEdit \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qplaintextedit.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qtextedit.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qabstractscrollarea.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qframe.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qtextoption.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qtextcursor.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qtextformat.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qpen.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qabstracttextdocumentlayout.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qtextlayout.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qglyphrun.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qrawfont.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qfontdatabase.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QSharedPointer \
		../../../tmp/qtcreator-3.0/src/libs/extensionsystem/pluginmanager.h \
		../../../tmp/qtcreator-3.0/src/libs/aggregation/aggregate.h \
		../../../tmp/qtcreator-3.0/src/libs/aggregation/aggregation_global.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QHash \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QReadWriteLock \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qreadwritelock.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QReadLocker \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QStringList \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/QListWidget \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qlistwidget.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qlistview.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qabstractitemview.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qitemselectionmodel.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qabstractitemdelegate.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qstyleoption.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qabstractspinbox.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qvalidator.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qregularexpression.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qslider.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qabstractslider.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qstyle.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qtabbar.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qtabwidget.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qrubberband.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/QAction \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/QMessageBox \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qmessagebox.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qdialog.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/QMainWindow \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qmainwindow.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/QApplication \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qapplication.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qcoreapplication.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/qeventloop.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtWidgets/qdesktopwidget.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qguiapplication.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qinputmethod.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QDebug \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/QPainter \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qpainter.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/QTextBlock \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtGui/qtextobject.h \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QChar \
		../../../Qt5.1.1/5.1.1/clang_64/include/QtCore/QPair \
		.moc/release-shared/easymotionplugin.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/easymotionplugin.o easymotionplugin.cpp

.obj/release-shared/moc_easymotionplugin.o: .moc/release-shared/moc_easymotionplugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/moc_easymotionplugin.o .moc/release-shared/moc_easymotionplugin.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

